spring:
  profiles:
    active: test
  datasource:
    url: jdbc:sqlserver://ltd-db-server.database.windows.net:1433;database=LTD_DB;user=ltddbadmin@ltd-db-server;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ltddbadmin
    password: ltdadmin@1
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.SQLServer2012Dialect
    namingStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  #-----H2 set up do not include in commits---------
  #     h2:
  #         console.enabled: true
  #     datasource:
  #         url: jdbc:h2:mem:mydb
  #         username: sa
  #         password: password
  #         driverClassName: org.h2.Driver
  #     jpa:
  #         database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: lpshris1@gmail.com
    password: xcmhecferfilhhmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
      verify:
         host: http://localhost:80
         login: http://localhost:4200/login
upload:
   files:
    path: C:/temp/files/
    extensions: jpg, jpeg, png, gif

servlet:
  multipart:
    max-file-size: 1000MB
    max-request-size: 2000MB
server:
  port: 80
management:
  server:
    endpoint:
      shutdown: 
      enabled: true
      web:
      exposure:
        include: "*"
