environment:
  name: test
spring:
  datasource:
    url: jdbc:sqlserver://192.168.10.58:1433;instanceName=MSSQLSERVER;databaseName=LDDBDEV;encrypt=true;trustServerCertificate=true
    username: lps
    password: 6E/T5h8=-frY
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.SQLServer2012Dialect
    namingStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 80
