spring:
    datasource:
        url: jdbc:sqlserver://192.168.10.87:1433;instanceName=MSSQLSERVER;databaseName=LDDBDEV;encrypt=true;trustServerCertificate=true
        username: LPS
        password: LPS
    jpa:
        show-sql: true
        hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        namingStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#-----H2 set up do not include in commits---------
#     h2:
#         console.enabled: true
#     datasource:
#         url: jdbc:h2:mem:mydb
#         username: sa
#         password: password
#         driverClassName: org.h2.Driver
#     jpa:
#         database-platform: org.hibernate.dialect.H2Dialect
    mail:
      host: smtp.gmail.com
      port: 587
      username: lpshris1@gmail.com
      password: xcmhecferfilhhmi
      properties:
        mail: 
         smtp: 
            auth: true
            starttls:
              enable: true
server: 
  port: 80
management:
  server:
    port: 9191
    endpoint:
      shutdown: 
      enabled: true
      web:
      exposure:
        include: "*"