environment:
  name: test
spring:
  datasource:
    url: jdbc:sqlserver://192.168.10.58:1433;instanceName=MSSQLSERVER;databaseName=LDDBDEV;encrypt=true;trustServerCertificate=true
    username: lps
    password: 6E/T5h8=-frY
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
       dialect: org.hibernate.dialect.SQLServer2012Dialect
       naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
   host: smtp.gmail.com
   port: 587
   username: lpshris1@gmail.com
   password: xcmhecferfilhhmi
   default-encoding: UTF-8
   properties:
      mail: 
        mime:
           charset: UTF
        smtp: 
           writetimeout: 10000
           connectiontimeout: 10000
           timeout: 10000
           auth: true
           starttls:
               enable: true
               required: true
   verify:
      host: http://localhost:9191
      login: http://localhost:4200/login  
server:
  port: 9191
