environment:
   name: dev
spring:
   datasource:
      url: jdbc:sqlserver://127.0.0.1:1433;instanceName=MSSQLSERVER;databaseName=LDDBDEV;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
   jpa:
        show-sql: true
        hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        namingStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB
server: 
  port: 80
  tomcat:
       max-swallow-size: 1000MB